services:
  app:
    container_name: home-library
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: sh -c "npx prisma migrate deploy && npm run start:prod"
    depends_on:
      - db
    working_dir: /app
    ports:
      - ${PORT}:${PORT}
    networks:
      - home-library-network
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    restart: always
    # platform: linux/amd64
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: home-library-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgress-db:/var/lib/postgresql/data
    networks:
      - home-library-network
    restart: always

volumes:
  postgress-db:

networks:
  home-library-network:
    driver: bridge